MediConnect/urls.py
from django.contrib import admin
from django.urls import include, path
from MediConnect import settings
from mainapp.views import *
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name="index"),

    path('register/', register, name='register'),

    path('login/', login_view, name='login'),

    path('logout/', LogoutView.as_view(next_page='profile'), name='logout'),

    path('profile/', profile, name='profile'),

    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html'), name='password_reset'),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_sent.html'), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html'), name='password_reset_confirm'),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'), name='password_reset_complete'),
    path("chatbot/", chatbot, name="chatbot"),

    path('schedule-appointment/', schedule_appointment,
         name='schedule_appointment'),

    path('appointment/<int:appointment_id>/edit/',
         edit_appointment, name='edit_appointment'),

    path('appointment/<int:appointment_id>/delete/',
         delete_appointment, name='delete_appointment'),
]

mainapp/models.py
import datetime
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import Group

doctor_group, _ = Group.objects.get_or_create(name='Doctor')
nurse_group, _ = Group.objects.get_or_create(name='Nurse')
patient_group, _ = Group.objects.get_or_create(name='Patient')


def send_email_critical_updates(modeladmin, request, queryset):
    for appointment in queryset:
        subject = 'Critical Updates'
        message = f"""
            <html>
                <head>
                    <title>{subject}</title>
                    <style>
                        h1 {{
                            text-align: center;
                            margin-top: 0;
                            margin-bottom: 1rem;
                            color: red;
                        }}
                    </style>
                </head>
                <body>
                    <h1>{subject}</h1>
                    <p>please check the website for the new updates. </p>
                </body>
            </html>
        """
        from_email = 'bakermrad0@django.com'
        recipient_list = [appointment.patient.user.email]
        send_mail(subject, message, from_email, recipient_list, html_message=message)
    modeladmin.message_user(request, f'Successfully sent {queryset.count()} emails.')


send_email_critical_updates.short_description = 'send_email_critical_updates'


def send_email_Appointment_Reminder(modeladmin, request, queryset):
    for appointment in queryset:
        subject = 'Appointment Reminder'
        message = f"""
            <html>
                <head>
                    <title>{subject}</title>
                    <style>
                        table {{
                            border-collapse: collapse;
                            width: 100%;
                            max-width: 600px;
                            margin: 0 auto;
                        }}
                        th, td {{
                            text-align: left;
                            padding: 8px;
                            border-bottom: 1px solid #ddd;
                        }}
                        th {{
                            background-color: #f2f2f2;
                        }}
                        h1 {{
                            text-align: center;
                            margin-top: 0;
                            margin-bottom: 1rem;
                            color: red;
                        }}
                    </style>
                </head>
                <body>
                    <h1>{subject}</h1>
                    <table>
                        <tr>
                            <th>Doctor</th>
                            <td>{appointment.doctor.user.username}</td>
                        </tr>
                        <tr>
                            <th>Patient</th>
                            <td>{appointment.patient.user.username}</td>
                        </tr>
                        <tr>
                            <th>Date</th>
                            <td>{appointment.appoint_date}</td>
                        </tr>
                        <tr>
                            <th>Time</th>
                            <td>{appointment.appoint_time}</td>
                        </tr>
                    </table>
                </body>
            </html>
        """

        from_email = 'bakermrad0@gmail.com'
        recipient_list = [appointment.patient.user.email]
        send_mail(subject, message, from_email, recipient_list, html_message=message)
    
    modeladmin.message_user(request, f'Successfully sent {queryset.count()} emails.')

send_email_Appointment_Reminder.short_description = 'send_email_Appointment_Reminder'

def send_email_important_announcements(modeladmin, request, queryset):
    for appointment in queryset:
        subject = 'Important Announcements'
        message = f"""
            <html>
                <head>
                    <title>{subject}</title>
                    <style>
                        table {{
                            border-collapse: collapse;
                            width: 100%;
                            max-width: 600px;
                            margin: 0 auto;
                        }}
                        th, td {{
                            text-align: left;
                            padding: 8px;
                            border-bottom: 1px solid #ddd;
                        }}
                        th {{
                            background-color: #f2f2f2;
                        }}
                        h1 {{
                            text-align: center;
                            margin-top: 0;
                            margin-bottom: 1rem;
                            color: red;
                        }}
                    </style>
                </head>
                <body>
                    <h1>{subject}</h1>
                    <p>Hi {appointment.patient.user.username}, we have an important anouncements please check your account to learn more.</p>
                </body>
            </html>
        """
        from_email = 'bakermrad0@gmail.com'
        recipient_list = [appointment.patient.user.email]
        send_mail(subject, message, from_email, recipient_list, html_message=message)
    modeladmin.message_user(
        request, f'Successfully sent {queryset.count()} emails.')


send_email_important_announcements.short_description = 'send_email_important_announcements'


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    specialty = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username


class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField()
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username

    @property
    def age(self):
        today = datetime.date.today()
        age = today.year - self.dob.year
        if today < datetime.date(today.year, self.dob.month, self.dob.day):
            age -= 1
        return age


class Nurse(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username

    @property
    def email(self):
        return self.user.email


class Appointment(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    nurse = models.ForeignKey(Nurse, on_delete=models.CASCADE)
    appoint_date = models.DateField()
    appoint_time = models.TimeField()
    treatment = models.TextField()

    def __str__(self):
        return f"{self.patient}, {self.doctor}"

mainapp/forms.py
from django import forms
from .models import Appointment



class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['doctor', 'nurse', 'appoint_date',
                  'appoint_time', 'treatment']

        widgets = {
            'appoint_date': forms.DateInput(attrs={'type': 'date', 'class': 'input'}),
            'appoint_time': forms.TimeInput(attrs={'type': 'time', 'class': 'input'}),
            'doctor': forms.Select(attrs={'class': 'input'}),
            'nurse': forms.Select(attrs={'class': 'input'}),
            'treatment': forms.Textarea(attrs={'class': 'input', 'rows': 4}),
        }

mainapp/views.py
from .models import Appointment
from django.shortcuts import render, get_object_or_404, redirect
from .forms import AppointmentForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login
from django.views import View
from django.contrib.auth.models import Group
import openai
import os
from dotenv import load_dotenv

load_dotenv()

api_key = os.getenv("OPENAI_KEY", None)


def chatbot(request):
    chatbot_response = None
    if api_key is not None and request.method == 'POST':
        openai.api_key = api_key
        user_input = request.POST.get('user_input')
        prompt = f" {user_input}"

        response = openai.Completion.create(
            engine='text-davinci-003',
            prompt=prompt,
            max_tokens=250,
            stop=".",
            temperature=0.5
        )
        print(response)

        chatbot_response = response["choices"][0]["text"]

    return render(request, 'chatbot.html', {"response": chatbot_response})


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            group = request.POST.get('group')
            selected_group = Group.objects.get(name=group)
            user.groups.add(selected_group)
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})


def login_view(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        if request.method == 'POST':
            form = AuthenticationForm(request, data=request.POST)
            if form.is_valid():
                user = form.get_user()
                login(request, user)
                return redirect('/')
        else:
            form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


@login_required(login_url='login')
def profile(request):
    return render(request, 'profile.html')


def index(request):
    return render(request, 'index.html')


def schedule_appointment(request):
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            appointment = form.save(commit=False)
            appointment.patient = request.user.patient
            appointment.save()
            return redirect('../')
    else:
        form = AppointmentForm()
    return render(request, 'appointment.html', {'form': form})


def edit_appointment(request, appointment_id):
    appointment = get_object_or_404(Appointment, id=appointment_id)
    if request.method == 'POST':
        form = AppointmentForm(request.POST, instance=appointment)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = AppointmentForm(instance=appointment)
    return render(request, 'edit_appointment.html', {'form': form})


def delete_appointment(request, appointment_id):
    appointment = get_object_or_404(Appointment, id=appointment_id)
    if request.method == 'POST':
        appointment.delete()
        return redirect('profile')
    return render(request, 'delete_appointment.html', {'appointment': appointment})

mainapp/templates/appointment.html
{% extends 'base.html' %}


{% load static %}


{% block title %}
Appointment
{% endblock %}

{% block style %}
<style>
body{
    background-color: #cdfef2 ;
}
.container {
    display: flex;
    justify-content: center; 
    align-items: center; 
    height: 100vh;
}      
.form {
    display: flex;
    flex-direction: column;
    gap: 10px;
    max-width: 700px;
    background-color: #fff;
    padding: 20px;
    border-radius: 20px;
    position: relative;
  }
  label{
    font-size: 18px;
    padding: 6px;
  }
  .title {
    font-size: 28px;
    color: #02503c;
    font-weight: 600;
    letter-spacing: -1px;
    position: relative;
    display: flex;
    align-items: center;
    padding-left: 30px;
  }
  
  .title::before,
  .title::after {
    position: absolute;
    content: "";
    height: 16px;
    width: 16px;
    border-radius: 50%;
    left: 0px;
    background-color: #02503c;
  }
  
  .title::before {
    width: 18px;
    height: 18px;
    background-color: #02503c;
  }
  
.input{
  width: 100%;
  padding: 10px;
  background-color: #cdfef2;
  color: #120b3c;
  border: none;
  border-radius: 10px;
  cursor: pointer;
  }

  
 .submit {
    padding: 15px 25px;
    border: unset;
    border-radius: 15px;
    color: #02503c;
    z-index: 1;
    background: #e8e8e8;
    position: relative;
    font-weight: 1000;
    font-size: 17px;
    -webkit-box-shadow: 4px 8px 19px -3px rgba(0,0,0,0.27);
    box-shadow: 4px 8px 19px -3px rgba(0,0,0,0.27);
    transition: all 250ms;
    overflow: hidden;
   }
   
   .submit::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    height: 100%;
    width: 0;
    border-radius: 15px;
    background-color: #02503c;
    z-index: -1;
    -webkit-box-shadow: 4px 8px 19px -3px rgba(0,0,0,0.27);
    box-shadow: 4px 8px 19px -3px rgba(0,0,0,0.27);
    transition: all 250ms
   }
   
   .submit:hover {
    color: #e8e8e8;
   }
   
   .submit:hover::before {
    width: 100%;
   }
  
  @keyframes pulse {
    from {
      transform: scale(0.9);
      opacity: 1;
    }
  
    to {
      transform: scale(1.8);
      opacity: 0;
    }
  }
</style>
{% comment %} 
Primary: #e4e1f9 (RGB: 228, 225, 249)
Secondary: #0c0727 (RGB: 12, 7, 39)
Primary Button: #9e8fff (RGB: 158, 143, 255)
Secondary Button: #120b3c (RGB: 18, 11, 60)
Accent: #5338ff (RGB: 83, 56, 255) {% endcomment %}

{% endblock style %}

{% block Page_Body %}
<div class="container">
    <div class="form">
        <h1 class="title">Schedule Appointment</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <center>
            <button type="submit" class="submit">Schedule</button>
            </center>
        </form>
    </div>

</div>
</body>
</html>


{% endblock %}

mainapp/templates/chatbot.html
{% extends 'base.html' %}


{% block title %}
chatbot
{% endblock %}
{% block style %}

{% comment %} 
Primary: #e4e1f9 (RGB: 228, 225, 249)
Secondary: #0c0727 (RGB: 12, 7, 39)
Primary Button: #9e8fff (RGB: 158, 143, 255)
Secondary Button: #120b3c (RGB: 18, 11, 60)
Accent: #5338ff (RGB: 83, 56, 255) {% endcomment %}
<style>
body{
    background-color: #cdfef2;
}
</style> {% endblock style %}

{% block Page_Body %}
<div class="flex justify-center items-center h-screen">
  <div class="max-w-md p-6 bg-white rounded-lg shadow-lg">
    <h1 class="text-3xl font-bold text-center mb-2">Enter the name of your disease</h1>

    <form method="POST">
      {% csrf_token %}
      <input type="text" name="user_input" class="w-full px-4 py-2 mb-4 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500">
      <button type="submit" class="w-full px-4 py-2 bg-[#3cb46e] text-white font-semibold rounded-md hover:bg-[#02503c]">Submit</button>
    </form>

    {% if response %}
    <div class="mt-4">
      {{ response | safe }}
    </div>
    {% endif %}
  </div>
</div>
{% endblock Page_Body %}

mainapp/templates/delete_appointment.html
{% extends 'base.html' %}

{% block title %}
Delete Appointment
{% endblock %}
{% block style %}

<style>

.form-container {
max-width: 400px;
margin: 0 auto;
padding: 20px;
background-color: #cdfef2;
border-radius: 4px;
}

/* Form input styles */
.form-container label {
display: block;
margin-bottom: 10px;
font-weight: bold;
}
.errorlist{
  color: red;
}
.form-container input[type="text"],
.form-container input[type="password"] {
width: 100%;
padding: 10px;
margin-bottom: 10px;
border: 1px solid #ccc;
border-radius: 4px;
}

.form-container button[type="submit"] {
  margin: 10px;
padding: 10px;
background-color: #02503c;
color: #fff;
border: none;
border-radius: 4px;
cursor: pointer;
}
</style> {% endblock style %}

{% block Page_Body %}
<form method="post" class="form-container" >
  {% csrf_token %}
  <h1>Delete Appointment</h1>
  <p>Are you sure you want to delete the appointment?</p>
  <center>
  <button type="submit">Delete</button>
</center>
</form>
{% endblock %}

mainapp/templates/edit_appointment.html
{% extends 'base.html' %}

{% block title %}
Edit Appointment
{% endblock %}
{% block style %}

{% comment %} 
Primary: #e4e1f9 (RGB: 228, 225, 249)
Secondary: #0c0727 (RGB: 12, 7, 39)
Primary Button: #9e8fff (RGB: 158, 143, 255)
Secondary Button: #120b3c (RGB: 18, 11, 60)
Accent: #5338ff (RGB: 83, 56, 255) {% endcomment %}
<style>
  /* styles.css */

/* Form container */
.form-container {
max-width: 400px;
margin: 0 auto;
padding: 20px;
background-color: #cdfef2;
border-radius: 4px;
}

/* Form input styles */
.form-container label {
display: block;
margin-bottom: 10px;
font-weight: bold;
}
.errorlist{
  color: red;
}
.form-container input[type="text"],
.form-container input[type="password"] {
width: 100%;
padding: 10px;
margin-bottom: 10px;
border: 1px solid #ccc;
border-radius: 4px;
}

.form-container button[type="submit"] {
padding: 10px;
background-color: #02503c;
color: #fff;
border: none;
border-radius: 4px;
cursor: pointer;
}
</style> {% endblock style %}
{% block Page_Body %}
<center>
<h1 class="text-[#3cb46e] font-bold text-3xl mb-4" >Edit Appointment</h1>
</center>
<form class="form-container" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <center>
  <button type="submit">Save</button>
  </center>
</form>
{% endblock %}

mainapp/templates/index.html
{% extends 'base.html' %}


{% load static %}


{% block title %}
Home Page
{% endblock %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<style>
  .cssbuttons-io-button {
    background: #3cb46e;
    color: white;
    font-family: inherit;
    padding: 0.35em;
    padding-left: 1.2em;
    font-size: 17px;
    font-weight: 500;
    border-radius: 0.9em;
    border: none;
    letter-spacing: 0.05em;
    display: flex;
    align-items: center;
    box-shadow: inset 0 0 1.6em -0.6em #3cb46e;
    overflow: hidden;
    position: relative;
    height: 2.8em;
    padding-right: 3.3em;
}

.cssbuttons-io-button .icon {
    background: white;
    margin-left: 1em;
    position: absolute;
    display: flex;
    align-items: center;
    justify-content: center;
    height: 2.2em;
    width: 2.2em;
    border-radius: 0.7em;
    box-shadow: 0.1em 0.1em 0.6em 0.2em #3cb46e;
    right: 0.3em;
    transition: all 0.3s;
}

.cssbuttons-io-button:hover .icon {
    width: calc(100% - 0.6em);
}

.cssbuttons-io-button .icon svg {
    width: 1.1em;
    transition: transform 0.3s;
    color: #3cb46e;
}

.cssbuttons-io-button:hover .icon svg {
    transform: translateX(0.1em);
}

.cssbuttons-io-button:active .icon {
    transform: scale(0.95);
}
</style>
{% endblock %}


{% block Page_Body %}
<div>
<center>
  <div class="hero ">
    <center class="py-4 heroelements">
    <h1 class="px-2 text-[#120b3c] text-2xl" >Welcome to  </h1>
    <h1 class="px-2 text-[#d9f3f3] text-3xl sm:text-lg md:text-lg lg:text-7xl p-2 rounded bg-[#02503c]">MediConnect</h1>

    </center>
  </div>
  
  <div class="p-4 bg-gray-100 rounded-lg shadow-lg">
    <h1 class="text-3xl font-bold text-white bg-[#02503c] py-3 px-4 mb-4 rounded-lg">Our AI Chatbot</h1>
    <h2 class="text-xl font-semibold mb-4">Enter the name of your disease?</h2>
    <h2 class="text-lg mb-6">Enter the name of the disease and the chatbot will provide you with all the symptoms.</h2>
    {% comment %} <a href="{% url 'chatbot' %}" class="text-lg inline-block px-6 py-3 font-semibold bg-[#9e8fff] text-white rounded-lg hover:bg-blue-700 transition-colors duration-300">Go to Chatbot</a> {% endcomment %}
    <a href="{% url 'chatbot' %}"><button class="cssbuttons-io-button">Go to Chatbot
      <div class="icon">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"></path><path fill="currentColor" d="M16.172 11l-5.364-5.364 1.414-1.414L20 12l-7.778 7.778-1.414-1.414L16.172 13H4v-2z"></path>
        </svg>
      </div>
    </button></a>
  </div>
  
  
</center>




</div>
</body>
</html>
{% endblock %}  

{% comment %} 
Primary: #e4e1f9 (RGB: 228, 225, 249)
Secondary: #0c0727 (RGB: 12, 7, 39)
Primary Button: #9e8fff (RGB: 158, 143, 255)
Secondary Button: #120b3c (RGB: 18, 11, 60)
Accent: #5338ff (RGB: 83, 56, 255) {% endcomment %}

mainapp/templates/login.html
{% extends 'base.html' %}

{% block title %}
password_reset
{% endblock %}

{% block style %}

{% comment %} 
Primary: #e4e1f9 (RGB: 228, 225, 249)
Secondary: #0c0727 (RGB: 12, 7, 39)
Primary Button: #9e8fff (RGB: 158, 143, 255)
Secondary Button: #120b3c (RGB: 18, 11, 60)
Accent: #5338ff (RGB: 83, 56, 255) {% endcomment %}
<style>
  /* styles.css */

/* Form container */

.form-container {
max-width: 400px;
margin: 0 auto;
padding: 20px;
background-color: #cdfef2;
border-radius: 4px;
}

/* Form input styles */
.form-container label {
display: block;
margin-bottom: 10px;
font-weight: bold;
}
.errorlist{
  color: red;
}
.form-container input[type="text"],
.form-container input[type="password"] {
width: 100%;
padding: 10px;
margin-bottom: 10px;
border: 1px solid #ccc;
border-radius: 4px;
}

.form-container button[type="submit"] {
padding: 10px;
background-color: #3cb46e;
color: #fff;
border: none;
border-radius: 4px;
cursor: pointer;
}
</style> {% endblock style %}
{% block Page_Body %}

    <div class="flex items-center justify-center">
      <h1 class="text-3xl py-8 font-bold mb-8"  >Login</h1>
    </div>
    <div class="form-container">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}


      <center>
        <button type="submit">Login</button>
      </center>
    
    
      </form>
  
        <p class="social-text"><a href="{% url 'password_reset' %}">Forgot Password?</a></p>

    </div>
</body>
</html>


{% endblock %}  

mainapp/templates/password_reset_complete.html
{% extends 'base.html' %}


{% load static %}


{% block title %}
password_reset_complete
{% endblock %}

{% block Page_Body %}
<div>
<center>
    <h2>Password Reset Complete</h2>
    <p>Your password has been successfully reset. You can now <a class="bg-[#9e8fff] p-1 rounded" href="{% url 'login' %}">sign-in</a> with your new password.</p>
</center>
</div>
</body>
</html>
{% endblock %}  

mainapp/templates/password_reset_sent.html
{% extends 'base.html' %}

{% block title %}
Reset password
{% endblock %}

{% block Page_Body %}
<div>
<center>
    <h2>Password Reset Email Sent</h2>
    <p>An email has been sent to your registered email address with further instructions to reset your password. Please check your inbox.</p>
    
</center>  
</div>
</body>
</html>
{% endblock %}  

mainapp/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Profile Page
{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">

<style>
  .card {
    width: 10vw;
    height: 10vh;
    background:  #cdfef2;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 2em;
    color: #333;
    font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
    border-radius: 40px;
    cursor: pointer;
    position: relative;
    transition: all 0.7s ease-in-out;
    overflow: hidden;
  }
  
  .card::before {
    content: "";
    position: absolute;
    height: 40%;
    width: 100%;
    background-color: #02503c;
    bottom: 0;
    right: 0;
    transform: translatey(70px);
    border-radius: 100%;
    transition: all 0.7s ease-in-out;
  }
  
  .c-txt {
    z-index: 2;
  }
  
  .card:hover::before {
    transform: scale(7) translate(-50px);
  }
  
  .card:hover {
    box-shadow: 1px -10px 50px 50px #02503c;
    color: #f3f3f3;
  }
  
</style>
{% endblock %}

{% block Page_Body %}

<div class="form-container">
  {% if user.is_authenticated %}
  <center>
    <h1 class="text-[#3cb46e] font-bold text-3xl mb-4">Welcome, {{ user.username }} to your profile!</h1>
  </center>

  <center>
    <h2 class="text-[#02503c] font-serif p-4 font-bold text-lg">Your Appointments</h2>
  </center>

  <div class="overflow-x-auto">
    <table class="w-full divide-y divide-gray-200">
      <thead class="bg-[#cdfef2]">
        <tr>
          <th class="px-6 py-3 text-[#02503c] text-left text-xs font-medium uppercase tracking-wider">Nurse</th>
          <th class="px-6 py-3 text-[#02503c] text-left text-xs font-medium uppercase tracking-wider">Doctor</th>
          <th class="px-6 py-3 text-[#02503c] text-left text-xs font-medium uppercase tracking-wider">Date</th>
          <th class="px-6 py-3 text-[#02503c] text-left text-xs font-medium uppercase tracking-wider">Time</th>
          <th class="px-6 py-3 text-[#02503c] text-left text-xs font-medium uppercase tracking-wider">Description</th>
          <th class="px-6 py-3 text-[#02503c] text-left text-xs font-medium uppercase tracking-wider">Edit</th>
          <th class="px-6 py-3 text-[#02503c] text-left text-xs font-medium uppercase tracking-wider">Delete</th>
        </tr>
      </thead>
      <tbody class="bg-gray-200 divide-y divide-gray-200">
        {% for appointment in user.patient.appointment_set.all %}
        <tr>
          <td class="px-6 py-4 whitespace-nowrap">{{ appointment.doctor }}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{ appointment.nurse }}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{ appointment.appoint_date }}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{ appointment.appoint_time }}</td>
          <td class="px-6 py-4 whitespace-nowrap">{{ appointment.treatment }}</td>
          <td class="px-6 py-4 whitespace-nowrap">
            <a href="{% url 'edit_appointment' appointment.id %}" class="text-blue-500 underline">Edit</a>
          </td>
          <td class="px-6 py-4 whitespace-nowrap">
            <a href="{% url 'delete_appointment' appointment.id %}" class="text-red-500 underline">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  {% else %}
  <p class="text-center">You are not logged in.</p>
  <div class="flex justify-center mt-4">
    <a href="{% url 'login' %}" class="text-blue-500 underline mr-4">Login</a>
    <a href="{% url 'register' %}" class="text-blue-500 underline">Register</a>
  </div>
  {% endif %}

</div>



<center>
  <h1 class="text-2xl font-bold p-8 text-[#3cb46e] mr-4">Do you want to book an appointment</h1>
  <div class="card">
  <a class="c-txt" href="{% url 'schedule_appointment' %}">click here</a>
  </div>
</center>
{% endblock %}